# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: lb-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: lb-app
#   template:
#     metadata:
#       labels:
#         app: lb-app
#     spec:
#       containers:
#         - name: lb-app
#           image: public.ecr.aws/nginx/nginx:1.19.6
#           ports:
#             - name: http
#               containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/z9d2n7e1/nginx:1.19.5
          ports:
            - name: http
              containerPort: 80